<?xml version="1.0" ?>
<robot name="x3_rov_macros" xmlns:xacro="http://www.ros.org/wiki/xacro">

   <!-- fin -->
    <xacro:macro name="fin" params="suffix parent_link origin_xyz rad len">

        <link name="Lfin_${suffix}">
            <collision>
                <origin rpy="0 ${pi/2} 0" xyz="${-len/4} 0 0"/>
                <geometry>
                    <cylinder radius="${rad}" length="${len/2}"/>
                </geometry>
            </collision>

            <visual>
                <origin rpy="0 ${pi/2} 0" xyz="${-len/4} 0 0"/>
                <geometry>
                    <cylinder radius="${rad}" length="${len/2}"/>
                </geometry>
                <material name="black"/>
            </visual>
        </link>

        <joint name="Jfin_${suffix}" type="fixed">
            <parent link="${parent_link}"/>
            <child link="Lfin_${suffix}"/>
            <origin xyz="${origin_xyz}" rpy="0 0 0"/>
            <axis xyz="0 0 0"/>
	    </joint>

    </xacro:macro>

    <!-- propeller -->
    <xacro:macro name="prop" params="suffix parent_link origin_xyz rad len mirror">

        <link name="Lprop_conn_${suffix}">
            <collision>
                <origin rpy="0 ${pi/2} 0" xyz="${-len/4} 0 0"/>
                <geometry>
                    <cylinder radius="${rad * 2/3}" length="${len/2}"/>
                </geometry>
            </collision>

            <visual>
                <origin rpy="0 ${pi/2} 0" xyz="${-len/4} 0 0"/>
                <geometry>
                    <cylinder radius="${rad * 2/3}" length="${len/2}"/>
                </geometry>
                <material name="black"/>
            </visual>
        </link>


        <joint name="Jprop_conn_${suffix}" type="fixed">
            <parent link="${parent_link}"/>
            <child link="Lprop_conn_${suffix}"/>
            <origin xyz="${origin_xyz}" rpy="0 0 0"/>
            <axis xyz="0 0 0"/>
        </joint>

        <link name="Lprop_body_${suffix}">
            <collision>
                <origin rpy="0 ${pi/2} 0" xyz="${-len/4} 0 0"/>
                <geometry>
                    <cylinder radius="${rad}" length="${len/2}"/>
                </geometry>
            </collision>

            <visual>
                <origin rpy="0 ${pi/2} 0" xyz="${-len/4} 0 0"/>
                <geometry>
                    <cylinder radius="${rad}" length="${len/2}"/>
                </geometry>
                <material name="black"/>
            </visual>
        </link>

        <joint name="Jprop_body_${suffix}" type="fixed">
            <parent link="Lprop_conn_${suffix}"/>
            <child link="Lprop_body_${suffix}"/>
            <origin xyz="${-len/2} ${mirror * rad * 1/3} 0" rpy="0 0 0"/>
            <axis xyz="0 0 0"/>
        </joint>

    </xacro:macro>

</robot>