<?xml version="1.0" ?>
<robot name="x3_rov_macros" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- * * * inertial calculations * * * -->
	<!-- sources: -->
	<!-- https://github.com/ros-industrial/universal_robot/blob/06d8b9e2f5f86aa54f9f2845f11edbc84e2f951e/ur_description/urdf/ur10.urdf.xacro#L12-L20 -->
	<!-- https://answers.ros.org/question/293281/using-xacro-to-automate-inertial-calculations-sequencefloat-error/ -->

	<!-- cuboid -->
	<xacro:macro name="cuboid_inertial" params="*origin mass length width height">
    <inertial>
      <mass value="${mass}"/>
			<xacro:insert_block name="origin" />

      <inertia
				ixx="${0.83 * mass * (width  + height)}" ixy="0.0" ixz="0.0" 
				iyy="${0.83 * mass * (length + height)}" iyz="0.0" 
				izz="${0.83 * mass * (width  + length)}" 
			/>
    </inertial>
  </xacro:macro>

	<!-- cylinder -->
	<xacro:macro name="cylinder_inertial" params="*origin mass radius length">
    <inertial>
      <mass value="${mass}" />
			<xacro:insert_block name="origin" />

      <inertia 
				ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
        izz="${0.5 * mass * radius * radius}" 
			/>
    </inertial>
  </xacro:macro>


	<!-- * * * macros for creating links * * * -->

	<!-- create fin and attach to parent -->
	<xacro:macro name="fin" params="suffix parent_link origin_xyz mass radius length">

		<link name="Lfin_${suffix}">

			<xacro:cylinder_inertial 
				mass="${mass}" 
				radius="${radius}"
				length="${length}" 
			>
				<origin xyz="${-length/2} 0 0" rpy="0 ${pi/2} 0"/>
			</xacro:cylinder_inertial>

			<collision>
				<origin xyz="${-length/2} 0 0" rpy="0 ${pi/2} 0"/>
				<geometry>
					<cylinder radius="${radius}" length="${length}"/>
				</geometry>
			</collision>

			<!-- <visual>
				<origin rpy="0 ${pi/2} 0" xyz="${-length/2} 0 0"/>
				<geometry>
					<cylinder radius="${radius}" length="${length}"/>
				</geometry>
				<material name="black"/>
			</visual> -->
		</link>


		<joint name="Jfin_${suffix}" type="fixed">
			<parent link="${parent_link}"/>
			<child link="Lfin_${suffix}"/>
			<origin xyz="${origin_xyz}" rpy="0 0 0"/>
			<axis xyz="0 0 0"/>
		</joint>

	</xacro:macro>

	<!-- create propeller and attach to parent -->
	<xacro:macro name="prop" params="suffix parent_link origin_xyz mass radius length mirror">

		<link name="Lprop_conn_${suffix}">

			<xacro:cylinder_inertial 
				mass="${mass * 1/3}"
				radius="${radius * 2/3}"
				length="${length/2}" 
			>
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0"/>
			</xacro:cylinder_inertial>

			<collision>
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0"/>
				<geometry>
					<cylinder radius="${radius * 2/3}" length="${length/2}"/>
				</geometry>
			</collision>

			<!-- <visual>
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0" />
				<geometry>
					<cylinder radius="${radius * 2/3}" length="${length/2}"/>
				</geometry>
				<material name="black"/>
			</visual> -->
		</link>


		<joint name="Jprop_conn_${suffix}" type="fixed">
			<parent link="${parent_link}"/>
			<child link="Lprop_conn_${suffix}"/>
			<origin xyz="${origin_xyz}" rpy="0 0 0"/>
			<axis xyz="0 0 0"/>
		</joint>


		<link name="Lprop_body_${suffix}">

			<xacro:cylinder_inertial 
				mass="${mass * 2/3}"
				radius="${radius}"
				length="${length/2}" 
			>
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0"/>
			</xacro:cylinder_inertial>

			<collision>
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0"/>
				<geometry>
					<cylinder radius="${radius}" length="${length/2}"/>
				</geometry>
			</collision>

			<!-- <visual>
				<origin xyz="${-length/4} 0 0 rpy="0 ${pi/2} 0""/>
				<geometry>
					<cylinder radius="${radius}" length="${length/2}"/>
				</geometry>
				<material name="black"/>
			</visual> -->
		</link>

		<joint name="Jprop_body_${suffix}" type="fixed">
			<parent link="Lprop_conn_${suffix}"/>
			<child link="Lprop_body_${suffix}"/>
			<origin xyz="${-length/2} ${mirror * radius * 1/8} 0" rpy="0 0 0"/>
			<axis xyz="0 0 0"/>
		</joint>

	</xacro:macro>

</robot>