<?xml version="1.0"?>
<robot name="x3_rov" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- includes -->
    <xacro:include filename="$(find rov_hil)/urdf/materials.xacro" />
    <xacro:include filename="$(find rov_hil)/urdf/macros.xacro" />

    <!-- properties -->
    <xacro:property name="x3_length" value="0.485" />
    <xacro:property name="x3_width" value="0.257" />
    <xacro:property name="x3_height" value="0.354" />

	<!-- * * * Link Definitions * * * -->
    <link name="Lhitbox">
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${x3_length} ${x3_width} ${x3_height}"/>
            </geometry>
        </collision>

        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="${x3_length} ${x3_width} ${x3_height}"/>
                <!-- <mesh filename="package://my_cobot/models/joint1.dae"/> -->
            </geometry>
            <material name="grey_transparent"/>
        </visual>
	</link>

    <link name="Lmain">
        <collision>
            <origin rpy="0 0 0" xyz="${x3_length * 3/16} 0 0"/>
            <geometry>
                <box size="${x3_length*5/8} ${x3_width * 3/5} ${x3_height}"/>
            </geometry>
        </collision>

        <visual>
            <origin rpy="0 0 0" xyz="${x3_length * 3/16} 0 0"/>
            <geometry>
                <box size="${x3_length*5/8} ${x3_width * 3/5} ${x3_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
	</link>

    <joint name="Jmain" type="fixed">
    	<parent link="Lhitbox"/>
    	<child link="Lmain"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>
	</joint>

    <xacro:fin  
        suffix="top"
        parent_link="Lmain"
        origin_xyz="0 0 ${x3_height*(1/2 - 1/6)}" 
        rad="${x3_height * 1/6}" 
        len="${x3_length}"/>

    <xacro:fin  
        suffix="bot"
        parent_link="Lmain"
        origin_xyz="0 0 ${-x3_height*(1/2 - 1/6)}" 
        rad="${x3_height * 1/6}" 
        len="${x3_length}"/>

    <xacro:prop 
        suffix="left" 
        parent_link="Lmain"
        origin_xyz="0 ${x3_width * 3/10} 0" 
        rad="${x3_height * 1/9}" 
        len="${x3_length * 1/3}" 
        mirror="1"/>

    <xacro:prop 
        suffix="right"
        parent_link="Lmain"
        origin_xyz="0 ${-(x3_width * 3/10)} 0" 
        rad="${x3_height * 1/9}" 
        len="${x3_length * 1/3}" 
        mirror="-1"/>

</robot>