<?xml version="1.0"?>
<robot name="x3_rov" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- includes -->
	<xacro:include filename="$(find rov_hil)/urdf/materials.xacro" />
	<xacro:include filename="$(find rov_hil)/urdf/macros.xacro" />

	<!-- properties/variables -->
	<xacro:property name="x3_length" value="0.485" />	<!-- m  -->
	<xacro:property name="x3_width"  value="0.257" /> <!-- m  -->
	<xacro:property name="x3_height" value="0.354" /> <!-- m  -->

	<xacro:property name="x3_mass"   value="9" />     <!-- kg -->
	<!-- calculations are based roughly on volume distribution -->
	<xacro:property name="x3_m_main" value="${x3_mass * 0.66}" />
	<xacro:property name="x3_m_fin"  value="${x3_mass * 0.14}" />
	<xacro:property name="x3_m_prop" value="${x3_mass * 0.03}" />


	<!-- * * * Link Definitions * * * -->

	<!-- Dummy link to suppress warnings about root link inertia -->
	<link name="dummy">
	</link>

	<link name="Lmain">

		<xacro:cuboid_inertial 
			mass="${x3_m_main}" 
			length="${x3_length}" 
			width="${x3_width}" 
			height="${x3_height}"
		>
			<origin xyz="${x3_length * 3/16} 0 0" rpy="0 0 0"/>
		</xacro:cuboid_inertial>

		<collision>
			<origin xyz="${x3_length * 3/16} 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${x3_length*5/8} ${x3_width * 3/5} ${x3_height}"/>
			</geometry>
		</collision>

		<visual>
			<!-- <origin rpy="0 0 0" xyz="${x3_length * 3/16} 0 0"/> -->
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<!-- <box size="${x3_length*5/8} ${x3_width * 3/5} ${x3_height}"/> -->
				<mesh filename="package://rov_hil/models/x3_low_poly_smoothed.dae"/>
			</geometry>
			<material name="grey_transparent"/>
		</visual>
	</link>


	<joint name="dummy_joint" type="fixed">
		<parent link="dummy"/>
		<child link="Lmain"/>
	</joint>


	<!-- top fin -->
	<xacro:fin
		suffix="top"
		parent_link="Lmain"
		origin_xyz="0 0 ${x3_height*(1/2 - 1/6)}"
		mass="${x3_m_fin}"
		radius="${x3_height * 1/6}"
		length="${x3_length/2}"
	/>
	<!-- bottom fin -->
	<xacro:fin
		suffix="bot"
		parent_link="Lmain"
		origin_xyz="0 0 ${-x3_height*(1/2 - 1/6)}"
		mass="${x3_m_fin}"
		radius="${x3_height * 1/6}"
		length="${x3_length/2}"
	/>
	<!-- left propeller -->
	<xacro:prop
		suffix="left"
		parent_link="Lmain"
		origin_xyz="0 ${x3_width * 3/10} 0"
		mass="${x3_m_prop}"
		radius="${x3_height * 1/8}"
		length="${x3_length * 1/3}"
		mirror="1"
	/>
	<!-- right propeller -->
	<xacro:prop
		suffix="right"
		parent_link="Lmain"
		origin_xyz="0 ${-(x3_width * 3/10)} 0"
		mass="${x3_m_prop}"
		radius="${x3_height * 1/8}"
		length="${x3_length * 1/3}"
		mirror="-1"
	/>

</robot>