<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Loading some constants -->
  <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro"/>
  <!-- Loading file with sensor macros -->
  <xacro:include filename="$(find uuv_sensor_ros_plugins)/urdf/sensor_snippets.xacro"/>
  <!-- Loading the UUV simulator ROS plugin macros -->
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>  
  <!-- Loading vehicle's specific macros -->
  <xacro:include filename="$(find x3_description)/urdf/snippets.xacro"/>

  <!--
    Vehicle's parameters
  -->

  <!-- Vehicle dimensions -->
  <xacro:property name="length" value="0.485" />	  <!-- m  -->
	<xacro:property name="width"  value="0.257" /> 	<!-- m  -->
	<xacro:property name="height" value="0.354" /> 	<!-- m  -->

  <xacro:property name="mass" value="9"/>
  <!-- Center of gravity -->
  <xacro:property name="cog" value="0 0 0"/>
  <!-- Fluid density -->
  <xacro:property name="rho" value="1028"/>

  <!-- Visual mesh -->
  <xacro:property name="visual_mesh_file" value="file://$(find x3_description)/meshes/vehicle.dae"/>

  <!-- Collision geometry mesh -->
  <!-- <xacro:property name="collision_mesh_file" value="file://$(find x3_description)/meshes/vehicle.stl"/> -->

  <!-- Vehicle macro -->
  <xacro:macro name="x3_base" params="namespace *gazebo">

      <!-- Rigid body description of the base link -->
      <link name="${namespace}/base_link">
        <xacro:box_inertial 
          mass="${mass}" 
          x="${length}" 
          y="${width * 4/5}" 
          z="${height}"
          >
          <origin xyz="${cog}" rpy="0 0 0"/>
		    </xacro:box_inertial>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="${visual_mesh_file}" scale="1 1 1" />
            <!-- <box size="${length*5/8} ${width * 3/5} ${height}"/> -->
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <!-- <mesh filename="${collision_mesh_file}" scale="1 1 1" /> -->
            <box size="${length*5/8} ${width * 3/5} ${height}"/>
          </geometry>
        </collision>
      </link>

    <gazebo reference="${namespace}/base_link">
      <selfCollide>false</selfCollide>
    </gazebo>

    <!-- Set up hydrodynamic plugin given as input parameter -->
    <xacro:insert_block name="gazebo"/>

    <!-- Include the thruster modules -->
    <xacro:include filename="$(find x3_description)/urdf/actuators.xacro"/>

    <!-- Include the sensor modules -->
    <xacro:include filename="$(find x3_description)/urdf/sensors.xacro"/>

  </xacro:macro>

</robot>
