<?xml version="1.0" ?>
<robot name="x3_components" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- includes -->
	<xacro:include filename="$(find rov_hil)/urdf/helpers.xacro" />

	<!-- properties/variables -->
	<xacro:arg name="debug" default="0"/>
	<xacro:arg name="namespace" default="x3_rov"/>
	<xacro:arg name="inertial_reference_frame" default="world"/>


	<!-- * * * hydrodynamic_model * * * -->
	<xacro:macro name="rov_hydro_model" params="parent_link mass length width height cob neutrally_buoyant">

		<gazebo>
			<plugin name="uuv_plugin" filename="libuuv_underwater_object_ros_plugin.so">
				<!-- Hydro parameters for the vehicle-->
				<fluid_density>1025.0</fluid_density>
				<flow_velocity_topic>hydrodynamics/current_velocity</flow_velocity_topic>
				<debug>$(arg debug)</debug>

				<link name="${parent_link}">
					<neutrally_buoyant>${neutrally_buoyant}</neutrally_buoyant>
					<volume>${mass/1025}</volume>
					<box>
						<width>${width}</width>
						<length>${length}</length>
						<height>${height}</height>
					</box>
					<center_of_buoyancy>${cob}</center_of_buoyancy>
					<hydrodynamic_model>
						<type>fossen</type>
						<added_mass>
						<!-- from papers fault tolerant observer design Mokleiv2017 -->
						<!-- and blueye pioneer bellingmo2020 -->
						<!-- some values are only estimations -->
							5.22     0     0    0    0    0
						   	   0 19.87     0    0    0    0
						   	   0 	 0 12.02    0    0    0
						   	   0     0     0 0.16    0    0
						   	   0     0     0    0 0.07    0
						   	   0     0     0    0    0 0.16
						</added_mass>
						<!-- Linear damping: see p.31 in Berg2012 -->
						<linear_damping>
						 -1.843 -3.1802 -0.3778 -0.0868 -0.04 -0.0868
						</linear_damping>
						<!-- Non-linear damping: see p.30 in Berg2012 -->
						<!-- <quadratic_damping>
						-9.4873 -45.7127 -25.4825 -0.5344 -0.2 -0.5344
						</quadratic_damping> -->
					</hydrodynamic_model>
				</link>
			</plugin>
		</gazebo>
	</xacro:macro>

	<!-- Thruster macro -->
	<xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro"/>
	<xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/thruster_snippets.xacro"/>
	<!-- Thruster model -->
	<xacro:property name="thruster_mesh_file" value="file://$(find rov_hil)/models/x3_low_poly_propeller.dae"/>
	<!-- Wrapper for thruster macro -->
	<xacro:macro name="thruster_macro" params="thruster_id *origin">
		<xacro:thruster_module_first_order_basic_fcn_macro
			namespace="$(arg namespace)"
			thruster_id="${thruster_id}"
			mesh_filename="${thruster_mesh_file}"
			dyn_time_constant="0.05"
			rotor_constant="0.000031"
			>
			<xacro:insert_block name="origin"/>
		</xacro:thruster_module_first_order_basic_fcn_macro>
	</xacro:macro>

	<!-- * * * macros for creating links * * * -->

	<!-- create fin and attach to parent -->
	<xacro:macro name="x3_fin" params="suffix parent_link origin_xyz mass radius length">
		<link name="$(arg namespace)/fin_${suffix}_link">
			<xacro:cylinder_inertial 
				mass="${mass}" 
				radius="${radius}"
				length="${length}" >
				<origin xyz="${-length/2} 0 0" rpy="0 ${pi/2} 0"/>
			</xacro:cylinder_inertial>
			<collision>
				<origin xyz="${-length/2} 0 0" rpy="0 ${pi/2} 0"/>
				<geometry>
					<cylinder radius="${radius}" length="${length}"/>
				</geometry>
			</collision>
			<visual>
				<origin rpy="0 ${pi/2} 0" xyz="${-length/2} 0 0"/>
				<geometry>
					<cylinder radius="1e-5" length="1e-5"/>
				</geometry>
				<material name="black"/>
			</visual>
		</link>

		<joint name="$(arg namespace)/fin_${suffix}_joint" type="fixed">
			<parent link="${parent_link}"/>
			<child link="$(arg namespace)/fin_${suffix}_link"/>
			<origin xyz="${origin_xyz}" rpy="0 0 0"/>
			<axis xyz="0 0 0"/>
		</joint>

	</xacro:macro>

	<!-- create thruster housing and attach to parent -->
	<xacro:macro name="x3_thruster" params="suffix parent_link origin_xyz mass radius length mirror">
		<link name="$(arg namespace)/thruster_conn_${suffix}_link">
			<xacro:cylinder_inertial 
				mass="${mass * 1/3}"
				radius="${radius * 2/3}"
				length="${length/2}" >
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0"/>
			</xacro:cylinder_inertial>
			<collision>
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0"/>
				<geometry>
					<cylinder radius="${radius * 2/3}" length="${length/2}"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0" />
				<geometry>
					<cylinder radius="1e-5" length="1e-5"/>
				</geometry>
				<material name="black"/>
			</visual>
		</link>

		<joint name="$(arg namespace)/thruster_conn_${suffix}_joint" type="fixed">
			<parent link="${parent_link}"/>
			<child link="$(arg namespace)/thruster_conn_${suffix}_link"/>
			<origin xyz="${origin_xyz}" rpy="0 0 0"/>
			<axis xyz="0 0 0"/>
		</joint>

		<link name="$(arg namespace)/thruster_body_${suffix}_link">
			<xacro:cylinder_inertial 
				mass="${mass * 2/3}"
				radius="${radius}"
				length="${length/2}" >
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0"/>
			</xacro:cylinder_inertial>
			<collision>
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0"/>
				<geometry>
					<cylinder radius="${radius}" length="${length/2}"/>
				</geometry>
			</collision>
			<visual>
				<origin xyz="${-length/4} 0 0" rpy="0 ${pi/2} 0"/>
				<geometry>
					<cylinder radius="1e-5" length="1e-5"/>
				</geometry>
				<material name="black"/>
			</visual>
		</link>
		<joint name="$(arg namespace)/thruster_body_${suffix}_joint" type="fixed">
			<parent link="$(arg namespace)/thruster_conn_${suffix}_link"/>
			<child link="$(arg namespace)/thruster_body_${suffix}_link"/>
			<origin xyz="${-length/2} ${mirror * radius * 1/8} 0" rpy="0 0 0"/>
			<axis xyz="0 0 0"/>
		</joint>
	</xacro:macro>

</robot>