x3_rov:
  # joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # position controllers
  camera1/controller:
    type: effort_controllers/JointPositionController
    joint: x3_rov/camera1_joint
    pid: {p: 10.0, i: 1.0, d: 0.5}
    # pid: {p: 0.0, i: 0.0, d: 0.0}
